Repository Aparking/AparKing_Frontend, pull requests merged in 2024-05, with the labels that each got.

#65 feat: funcioalidad para añadir fecha y hora a la cesion de aparcamiento
  src/app/components/create-parking-modal/create-parking-modal.component.html
  src/app/components/create-parking-modal/create-parking-modal.component.ts
  src/app/components/parkingCesion/parkingCesion.component.html
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.ts
  src/app/models/parking.ts
  src/app/tab5/tab5-routing.module.ts
  src/app/tab5/tab5.module.ts
  src/app/tab5/tab5.page.html
  src/app/tab5/tab5.page.scss
  src/app/tab5/tab5.page.spec.ts
  src/app/tab5/tab5.page.ts
  src/app/tabs/tabs-routing.module.ts
  src/app/tabs/tabs.module.ts
  src/app/tabs/tabs.page.html
  src/app/tabs/tabs.page.ts
Labels: feat, g1

#66 errores visuales en el registro de vehiculo
  src/app/app-routing.module.ts
  src/app/components/profile/profile.component.ts
  src/app/components/registerVehicle/registerVehicle.component.html
  src/app/components/registerVehicle/registerVehicle.component.scss
  src/app/components/registerVehicle/registerVehicle.component.ts
  src/app/pages/registerVehicle/registerVehicle-routing.module.ts
  src/app/pages/registerVehicle/registerVehicle.module.ts
  src/app/tab3/tab3-routing.module.ts
  src/app/tab3/tab3.module.ts
Labels: fix, g1

#67 fix: change link of about us
  src/app/pages/register/register.page.html
  src/app/pages/start-page/start-page.page.html
  src/app/tabs/tabs.page.html
Labels: fix

#68 Comprobar plan contratado a la hora de crear un garaje
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/components/subscription/subscription.component.ts
Labels: fix

#71 feat: compra de creditos
  src/app/components/subscription/subscription.component.html
  src/app/components/subscription/subscription.component.ts
  src/app/service/data-management.service.ts
  src/app/service/rest.service.ts
Labels: feat, g1

#73 Acceso vista detalle de garaje
  src/app/components/rental/garage-detail/garage-detail.component.ts
Labels: fix

#74 Fix paying with cash
  src/app/components/rental/garage-book-create/garage-book-create.component.html
  src/app/components/rental/garage-book-create/garage-book-create.component.ts
Labels: fix, refactor

#75 Fix/cesiones y listado vehiculos con eleccion vehiculo/312
  src/app/components/parkingCesion/parkingCesion.component.ts
  src/app/components/registerVehicle/registerVehicle.component.html
  src/app/components/registerVehicle/registerVehicle.component.scss
  src/app/components/registerVehicle/registerVehicle.component.ts
  src/app/models/authentication.ts
  src/app/service/data-management.service.ts
  src/app/service/rest.service.ts
Labels: feat, g1

#79 fix: edicion de perfil de usuario
  src/app/components/profile/profile.component.ts
  src/app/service/rest.service.ts
Labels: fix, g1

#84 feat: added new page terms and conditions #347
  src/app/app-routing.module.ts
  src/app/pages/about-us/about-us-page.page.scss
  src/app/pages/register/register.page.html
  src/app/pages/terms-and-conditions/terms-and-conditions-page-routing.module.ts
  src/app/pages/terms-and-conditions/terms-and-conditions-page.module.ts
  src/app/pages/terms-and-conditions/terms-and-conditions-page.page.html
  src/app/pages/terms-and-conditions/terms-and-conditions-page.page.scss
  src/app/pages/terms-and-conditions/terms-and-conditions-page.page.ts
Labels: feat

#86 Fix vehicle form
  src/app/components/registerVehicle/registerVehicle.component.html
  src/app/components/registerVehicle/registerVehicle.component.ts
Labels: fix, g1

#90 Fix/validate forms/339
  src/app/components/registerVehicle/registerVehicle.component.html
  src/app/components/registerVehicle/registerVehicle.component.scss
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-create/garage-create.component.ts
Labels: fix, g1, g3

#93 fix: filtro de garages y check de mis garages
  src/app/components/rental/garage-create/garage-create.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.ts
Labels: fix, g1

#96 Añadir hora a la fecha de inicio y final de una reserva
  src/app/components/rental/garage-availability-list-create/garage-availability-list-create.component.html
  src/app/components/rental/garage-book-create/garage-book-create.component.html
Labels: feat, refactor

#95 Fix: Filter by disponible and AVAILABLE #372
  android/.gradle/8.0.2/checksums/checksums.lock
  android/.gradle/8.0.2/checksums/md5-checksums.bin
  android/.gradle/8.0.2/checksums/sha1-checksums.bin
  src/app/components/rental/garage-book-create/garage-book-create.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.ts
Labels: fix
