Repository Aparking/AparKing_Frontend, pull requests merged in 2024-03, with the labels that each got.

#7 Feat/register and session/1
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/usuarios/login/login.component.html
  src/app/usuarios/login/login.component.scss
  src/app/usuarios/login/login.component.spec.ts
  src/app/usuarios/login/login.component.ts
  src/app/usuarios/login/login.module.ts
  src/app/usuarios/login/login.service.spec.ts
  src/app/usuarios/login/login.service.ts
  src/app/usuarios/login/models/userLogin.models.ts
  src/app/usuarios/logout/logout.component.html
  src/app/usuarios/logout/logout.component.scss
  src/app/usuarios/logout/logout.component.spec.ts
  src/app/usuarios/logout/logout.component.ts
  src/app/usuarios/logout/logout.module.ts
  src/app/usuarios/logout/logout.service.spec.ts
  src/app/usuarios/logout/logout.service.ts
  src/app/usuarios/logout/models/userLogout.models.ts
  src/app/usuarios/register/models/user.models.ts
  src/app/usuarios/register/register.component.html
  src/app/usuarios/register/register.component.scss
  src/app/usuarios/register/register.component.spec.ts
  src/app/usuarios/register/register.component.ts
  src/app/usuarios/register/register.service.spec.ts
  src/app/usuarios/register/register.service.ts
Labels: feat

#11 Implementación del listado de administrador para los alquileres
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/rental/garage-detail/garage-detail.component.html
  src/app/components/rental/garage-detail/garage-detail.component.scss
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.scss
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/models/authentication.ts
  src/app/models/garagement.ts
  src/app/models/parking.ts
  src/app/services/rest.service.ts
  src/app/services/ws-astract.service.ts
  src/app/tab2/tab2.module.ts
  src/app/tab2/tab2.page.html
  src/app/tabs/tabs-routing.module.ts
  src/app/tabs/tabs.module.ts
  src/app/tabs/tabs.page.html
Labels: feat

#14 Implementación de lista de alquileres disponibles, filtros y mis garajes
  src/app/components/rental/available-garages/available-garages.component.html
  src/app/components/rental/available-garages/available-garages.component.scss
  src/app/components/rental/available-garages/available-garages.component.ts
  src/app/components/rental/my-garages/my-garages.component.html
  src/app/components/rental/my-garages/my-garages.component.scss
  src/app/components/rental/my-garages/my-garages.component.ts
  src/app/services/rest.service.ts
  src/app/tab2/tab2.page.html
  src/app/tab2/tab2.page.ts
  src/app/tabs/tabs.module.ts
Labels: feat

#16 Fusión del listado de garajes disponibles y del listado de garajes del administrador
  src/app/components/rental/available-garages/available-garages.component.html
  src/app/components/rental/available-garages/available-garages.component.scss
  src/app/components/rental/available-garages/available-garages.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.scss
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/tab2/tab2-routing.module.ts
  src/app/tab2/tab2.page.html
  src/app/tabs/tabs.module.ts
Labels: fix

#17 Feat/complete map implementation for parking zones/103
  .vscode/settings.json
  src/app/components/create-parking-modal/create-parking-modal.component.html
  src/app/components/create-parking-modal/create-parking-modal.component.scss
  src/app/components/create-parking-modal/create-parking-modal.component.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/models/parking.ts
  src/app/service/data-management.service.ts
  src/app/service/rest.service.ts
  src/app/service/websocket.service.ts
  src/app/service/ws-astract.service.ts
  src/app/tabs/tabs.module.ts
  src/app/tabs/tabs.page.html
Labels: feat, g1

#21 Creación de garaje e imágenes asociadas
  angular.json
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-create/garage-create.component.scss
  src/app/components/rental/garage-create/garage-create.component.spec.ts
  src/app/components/rental/garage-create/garage-create.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.html
  src/app/components/rental/garage-detail/garage-detail.component.scss
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/models/garagement.ts
  src/app/services/rest.service.ts
  src/app/tab2/tab2-routing.module.ts
  src/app/tab2/tab2.page.ts
  src/app/tabs/tabs.module.ts
  src/app/tabs/tabs.page.ts
Labels: feat, g3

#24 Creación de garajes con imágenes actualizados con el nuevo backend
  src/app/app-routing.module.ts
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-create/garage-create.component.ts
  src/app/services/rest.service.ts
  src/app/tab2/tab2-routing.module.ts
Labels: feat

#29 Config/deploy/171
  .gitignore
  src/app/pages/register/register.page.ts
  src/environments/environment.prod.ts
Labels: conf, deploy

#31 Edición y borrado de un anuncio de alquiler de garaje
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-create/garage-create.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.html
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/models/garagement.ts
  src/app/service/rest.service.ts
  src/app/tab2/tab2-routing.module.ts
Labels: feat, g3
