Repository Aparking/AparKing_Frontend, pull requests merged in 2024-04, with the labels that each got.

#19 Feat/pricing plans/12
  angular.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/pricing-plan/pricing-plan.component.html
  src/app/components/pricing-plan/pricing-plan.component.scss
  src/app/components/pricing-plan/pricing-plan.component.ts
  src/app/components/user-list/user-list.component.ts
  src/app/components/user-management/login/login.component.html
  src/app/components/user-management/login/login.component.scss
  src/app/components/user-management/login/login.component.ts
  src/app/components/user-management/logout/logout.component.html
  src/app/components/user-management/logout/logout.component.scss
  src/app/components/user-management/logout/logout.component.ts
  src/app/components/user-management/register/register.component.html
  src/app/components/user-management/register/register.component.scss
  src/app/components/user-management/register/register.component.ts
  src/app/models/pricing.models.ts
  src/app/models/user.models.ts
  src/app/models/userLogin.models.ts
  src/app/modules/login.module.ts
  src/app/modules/logout.module.ts
  src/app/modules/pricing-plan.module.ts
  src/app/service/auth-choice.service.ts
  src/app/service/login.service.ts
  src/app/service/logout.service.ts
  src/app/service/pricing-plan.service.ts
  src/app/service/register.service.ts
  src/app/service/user.service.ts
  src/app/service/ws-astract.service.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/app/tab2/auth-choice/auth-choice.component.html
  src/app/tab2/auth-choice/auth-choice.component.scss
  src/app/tab2/auth-choice/auth-choice.component.ts
  src/app/tab2/auth-choice/auth-choice.module.ts
  src/app/tab2/tab2.module.ts
  src/app/usuarios/login/login.component.spec.ts
  src/app/usuarios/login/login.service.spec.ts
  src/app/usuarios/login/login.service.ts
  src/app/usuarios/logout/logout.component.spec.ts
  src/app/usuarios/logout/logout.component.ts
  src/app/usuarios/logout/logout.service.spec.ts
  src/app/usuarios/logout/logout.service.ts
  src/app/usuarios/logout/models/userLogout.models.ts
  src/app/usuarios/register/models/user.models.ts
  src/app/usuarios/register/register.component.spec.ts
  src/app/usuarios/register/register.service.spec.ts
  src/app/usuarios/register/register.service.ts
Labels: feat, g1

#32 Feat/social media/30
  src/app/app-routing.module.ts
  src/app/pages/about-us/about-us-page-routing.module.ts
  src/app/pages/about-us/about-us-page.module.ts
  src/app/pages/about-us/about-us-page.page.html
  src/app/pages/about-us/about-us-page.page.scss
  src/app/pages/about-us/about-us-page.page.ts
  src/assets/icons/Alejandro.png
  src/assets/icons/alberto.png
  src/assets/icons/carmen.png
  src/assets/icons/enrique.png
  src/assets/icons/gmail.png
  src/assets/icons/insta.png
  src/assets/icons/ismael.png
  src/assets/icons/ivan.png
  src/assets/icons/jose.png
  src/assets/icons/juancarlos.png
  src/assets/icons/laura.png
  src/assets/icons/maria.png
  src/assets/icons/mario.png
  src/assets/icons/pedro.png
  src/assets/icons/sergio.png
  src/assets/icons/virgilio.png
Labels: feat

#33 Feat: About us page #28
  src/app/app-routing.module.ts
  src/app/pages/about-us/about-us-page-routing.module.ts
  src/app/pages/about-us/about-us-page.module.ts
  src/app/pages/about-us/about-us-page.page.html
  src/app/pages/about-us/about-us-page.page.scss
  src/app/pages/about-us/about-us-page.page.ts
  src/assets/icons/Alejandro.png
  src/assets/icons/alberto.png
  src/assets/icons/carmen.png
  src/assets/icons/enrique.png
  src/assets/icons/ismael.png
  src/assets/icons/ivan.png
  src/assets/icons/jose.png
  src/assets/icons/juancarlos.png
  src/assets/icons/laura.png
  src/assets/icons/maria.png
  src/assets/icons/mario.png
  src/assets/icons/pedro.png
  src/assets/icons/sergio.png
  src/assets/icons/virgilio.png
Labels: feat

#34 Implementacion de pasarela de pago para la membresia
  angular.json
  package-lock.json
  src/app/app-routing.module.ts
  src/app/components/payment/payment.service.spec.ts
  src/app/components/subscription/subscription.component.html
  src/app/components/subscription/subscription.component.scss
  src/app/components/subscription/subscription.component.spec.ts
  src/app/components/subscription/subscription.component.ts
  src/app/models/payments.ts
  src/app/service/data-management.service.ts
  src/app/service/payment.service.ts
  src/app/service/rest.service.ts
  src/app/service/ws-astract.service.ts
  src/app/tabs/tabs.module.ts
  src/app/tabs/tabs.page.html
  src/app/tabs/tabs.page.ts
  src/environments/environment.local.ts
  src/environments/environment.ts
  src/index.html
Labels: feat, g1

#37 Feat/law section/29
  src/app/pages/register/register.page.html
  src/app/pages/register/register.page.scss
Labels: feat

#36 Crear disponibilidad y alquilar por usuarios
  src/app/components/rental/garage-availability-list-create/garage-availability-list-create.component.html
  src/app/components/rental/garage-availability-list-create/garage-availability-list-create.component.scss
  src/app/components/rental/garage-availability-list-create/garage-availability-list-create.component.ts
  src/app/components/rental/garage-book-create/garage-book-create.component.html
  src/app/components/rental/garage-book-create/garage-book-create.component.ts
  src/app/components/rental/garage-book-list/garage-book-list.component.html
  src/app/components/rental/garage-book-list/garage-book-list.component.ts
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-create/garage-create.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.html
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/models/garagement.ts
  src/app/service/rest.service.ts
  src/app/tab2/tab2.module.ts
Labels: feat, fix

#42 fix: booking garage availabilities #7
  src/app/components/rental/garage-book-create/garage-book-create.component.html
  src/app/components/rental/garage-book-create/garage-book-create.component.ts
  src/app/components/rental/garage-book-list/garage-book-list.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.html
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/models/garagement.ts
Labels: fix, refactor

#44 feat: contact us added#30
  src/app/pages/about-us/about-us-page.page.html
Labels: epic

#45 Epic/parking management/14
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/map/map.component.html
  src/app/components/map/map.component.ts
  src/app/components/search-bar/search-bar.component.html
  src/app/components/search-bar/search-bar.component.ts
  src/app/components/search-bar/search-bar.componet.scss
  src/app/guards/need-auth.guard.ts
  src/app/models/parking.ts
  src/app/service/data-management.service.ts
  src/app/service/rest.service.ts
Labels: epic

#46 Feat/creacion vehiculo registro/240
  src/app/app-routing.module.ts
  src/app/models/authentication.ts
  src/app/pages/registerVehicle/registerVehicle-routing.module.ts
  src/app/pages/registerVehicle/registerVehicle.module.ts
  src/app/pages/registerVehicle/registerVehicle.page.html
  src/app/pages/registerVehicle/registerVehicle.page.scss
  src/app/pages/registerVehicle/registerVehicle.page.ts
  src/app/service/data-management.service.ts
  src/app/service/rest.service.ts
  src/app/tabs/tabs.page.html
  src/app/tabs/tabs.page.ts
Labels: feat, g1

#48 feat: added in start page link to page about us
  src/app/pages/start-page/start-page.page.html
Labels: feat

#49 Epic/app information
  src/app/app-routing.module.ts
  src/app/pages/about-us/about-us-page-routing.module.ts
  src/app/pages/about-us/about-us-page.module.ts
  src/app/pages/about-us/about-us-page.page.html
  src/app/pages/about-us/about-us-page.page.scss
  src/app/pages/about-us/about-us-page.page.ts
  src/app/pages/start-page/start-page.page.html
  src/assets/icons/Alejandro.png
  src/assets/icons/alberto.png
  src/assets/icons/carmen.png
  src/assets/icons/enrique.png
  src/assets/icons/gmail.png
  src/assets/icons/insta.png
  src/assets/icons/ismael.png
  src/assets/icons/ivan.png
  src/assets/icons/jose.png
  src/assets/icons/juancarlos.png
  src/assets/icons/laura.png
  src/assets/icons/maria.png
  src/assets/icons/mario.png
  src/assets/icons/pedro.png
  src/assets/icons/sergio.png
  src/assets/icons/virgilio.png
Labels: epic

#53 Fix/garage list filter/7
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-create/garage-create.component.scss
  src/app/components/rental/garage-create/garage-create.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/models/garagement.ts
  src/app/service/garage-state.service.ts
Labels: fix

#40 Arreglo de filtrado y listado
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/rental/garage-availability-list-create/garage-availability-list-create.component.html
  src/app/components/rental/garage-availability-list-create/garage-availability-list-create.component.scss
  src/app/components/rental/garage-availability-list-create/garage-availability-list-create.component.ts
  src/app/components/rental/garage-book-create/garage-book-create.component.html
  src/app/components/rental/garage-book-create/garage-book-create.component.ts
  src/app/components/rental/garage-book-list/garage-book-list.component.html
  src/app/components/rental/garage-book-list/garage-book-list.component.ts
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-create/garage-create.component.scss
  src/app/components/rental/garage-create/garage-create.component.spec.ts
  src/app/components/rental/garage-create/garage-create.component.ts
  src/app/components/rental/garage-detail/garage-detail.component.html
  src/app/components/rental/garage-detail/garage-detail.component.scss
  src/app/components/rental/garage-detail/garage-detail.component.ts
  src/app/components/rental/garage-list/garage-list.component.html
  src/app/components/rental/garage-list/garage-list.component.scss
  src/app/components/rental/garage-list/garage-list.component.ts
  src/app/components/rental/my-garages/my-garages.component.html
  src/app/components/rental/my-garages/my-garages.component.scss
  src/app/components/rental/my-garages/my-garages.component.ts
  src/app/models/garagement.ts
  src/app/pages/register/register.page.html
  src/app/service/data-management.service.ts
  src/app/service/garage-state.service.ts
  src/app/service/rest.service.ts
  src/app/tab2/tab2-routing.module.ts
  src/app/tab2/tab2.module.ts
  src/app/tab2/tab2.page.html
  src/app/tab2/tab2.page.ts
  src/app/tab3/tab3.page.html
  src/app/tabs/tabs-routing.module.ts
  src/app/tabs/tabs.module.ts
  src/app/tabs/tabs.page.html
  src/environments/environment.local.ts
  src/environments/environment.ts
  src/index.html
Labels: fix

#55 Vista de perfil usuario
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/components/add-user/add-user.component.html
  src/app/components/add-user/add-user.component.scss
  src/app/components/add-user/add-user.component.ts
  src/app/components/add-user/add-user.module.ts
  src/app/components/profile/profile.component.html
  src/app/components/profile/profile.component.scss
  src/app/components/profile/profile.component.ts
  src/app/components/user-details/user-details.component.html
  src/app/components/user-details/user-details.component.scss
  src/app/components/user-details/user-details.component.ts
  src/app/components/user-details/user-details.module.ts
  src/app/components/user-list/user-list.component.html
  src/app/components/user-list/user-list.component.scss
  src/app/components/user-list/user-list.component.spec.ts
  src/app/components/user-list/user-list.component.ts
  src/app/components/user-list/user-list.module.ts
  src/app/models/user.models.ts
  src/app/service/rest.service.ts
  src/app/services/user.service.spec.ts
  src/app/services/user.service.ts
  src/app/tab3/tab3.module.ts
  src/app/tab3/tab3.page.html
  src/app/tabs/tabs.page.html
  src/app/usuarios/login/login.component.html
  src/app/usuarios/login/login.component.scss
  src/app/usuarios/login/login.component.spec.ts
  src/app/usuarios/login/login.component.ts
  src/app/usuarios/login/login.module.ts
  src/app/usuarios/login/login.service.spec.ts
  src/app/usuarios/login/login.service.ts
  src/app/usuarios/login/models/userLogin.models.ts
  src/app/usuarios/logout/logout.component.html
  src/app/usuarios/logout/logout.component.scss
  src/app/usuarios/logout/logout.component.spec.ts
  src/app/usuarios/logout/logout.component.ts
  src/app/usuarios/logout/logout.module.ts
  src/app/usuarios/logout/logout.service.spec.ts
  src/app/usuarios/logout/logout.service.ts
  src/app/usuarios/logout/models/userLogout.models.ts
  src/app/usuarios/register/models/user.models.ts
  src/app/usuarios/register/register.component.html
  src/app/usuarios/register/register.component.scss
  src/app/usuarios/register/register.component.spec.ts
  src/app/usuarios/register/register.component.ts
  src/app/usuarios/register/register.service.spec.ts
  src/app/usuarios/register/register.service.ts
Labels: feat

#59 Develop
  src/app/pages/start-page/start-page.page.html
  src/app/pages/verify-user/verify-user.page.html
Labels: deploy

#60 Nuevo despliegue
  src/app/pages/start-page/start-page.page.html
  src/app/pages/verify-user/verify-user.page.html
Labels: deploy

#62 Arreglar cesión de plazas de aparcamiento #255
  src/app/components/parkingCesion/parkingCesion.component.html
  src/app/components/parkingCesion/parkingCesion.component.ts
  src/app/models/parking.ts
  src/app/service/data-management.service.ts
  src/app/service/rest.service.ts
  src/app/tab3/tab3.module.ts
  src/app/tab3/tab3.page.html
  src/app/tabs/tabs.module.ts
Labels: fix

#63 Fix: Refactor de botones intuitivos y textos erróneos
  src/app/components/create-parking-modal/create-parking-modal.component.html
  src/app/components/map/map.component.ts
  src/app/components/rental/garage-create/garage-create.component.html
  src/app/components/rental/garage-detail/garage-detail.component.html
  src/app/pages/verify-user/verify-user.page.html
Labels: fix, g3, refactor
